### ISSUE TITLE
`valid-values-license` not working

### ISSUE THREAD

**Issue by moshest** [tclindner/npm-package-json-lint#48]
npm-package-json-lint version: 2.7.0
npm version: 5.3.0
node version: 8.1.4

The output from npm-package-json-lint: 
```
Error: Error: valid-values-license - must be set to "error", "warning", or "off". Currently set to error,private
    at handleError (/Users/moshe/git/ventures/remote-lib/remote-lib/node_modules/npm-package-json-lint/src/cli.js:28:9)
    at Object.<anonymous> (/Users/moshe/git/ventures/remote-lib/remote-lib/node_modules/npm-package-json-lint/src/cli.js:126:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

What you expected to happen: Linting the license value.
The steps to reproduce the problem:
```json
{
  "rules": {
    "valid-values-license": ["error", [
      "private"
    ]]
  }
}

```

**Comment by tclindner** [comment]
Thank you for finding and reporting this bug, @moshest!! 👍
